export const options = {
    maxDt: 1000 / 20,
    fov: 45,
    pixelRatio: 0.5,
    walkSpeed: 1.5,
    turnSpeed: 4,
    firstPersonFov: 80,
    firstPersonHeight: 1.6,
    firstPersonSensitivity: .005,
    keyDirectionMapping: new Map([
        ['KeyW', 'up'],
        ['ArrowUp', 'up'],
        ['KeyA', 'left'],
        ['ArrowLeft', 'left'],
        ['KeyS', 'down'],
        ['ArrowDown', 'down'],
        ['KeyD', 'right'],
        ['ArrowRight', 'right'],
    ]),
}