export const options = {
    maxDt: 1000 / 20,
    fov: 45,
    pixelRatio: 0.5,
    walkSpeed: 6,
    turnSpeed: 4,
    firstPersonFov: 80,
    firstPersonHeight: 1.6,
    firstPersonSensitivity: .005,
    firstPersonKeyMapping: new Map([
        ['KeyW', 'up'],
        ['ArrowUp', 'up'],
        ['KeyA', 'left'],
        ['ArrowLeft', 'left'],
        ['KeyS', 'down'],
        ['ArrowDown', 'down'],
        ['KeyD', 'right'],
        ['ArrowRight', 'right'],
    ]),
    ditherThresholdMap: 'bluenoise.png',
}